[build]
  publish = "public"
  command = "npm i elm-spa@beta && npx elm-spa build"

[[redirects]]
  from = "/api/*"
  to = "https://conduit.productionready.io/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
